Determine height based on number of weeks in current month
christopherdro/react-native-calendar pull request #73
Opened 2016-10-20 22:27 UTC by hyb175

This is for https://github.com/christopherdro/react-native-calendar/issues/40.
Currently for scrollenabled, if there is one month with 6 weeks instead of 5 weeks, the scrollView will have height of 6 weeks in order to be able to contain all its children views. This change forces the scrollview to have the height of the current monthContainer instead of the month with biggest height.

2016-10-29 16:20 UTC, christopherdro requested changes

2016-10-29 16:20 UTC, christopherdro commented on components/styles.js
> +    height: DEVICE_WIDTH / 7,
Should this be DEVICE_HEIGHT?

2016-10-29 16:20 UTC, christopherdro commented on components/styles.js
> +
Move up top with other const

2016-10-29 16:20 UTC, christopherdro commented
Thanks for submitting this PR! I have a few comments before merging this in.

2016-10-31 17:02 UTC, hyb175 commented on components/styles.js
> +    height: DEVICE_WIDTH / 7,
I wanted to make it a square as a default, but maybe it should be something else.

2016-10-31 17:02 UTC, hyb175 commented on components/styles.js
> +
Roger that!

2016-10-31 17:10 UTC, christopherdro commented on components/styles.js
> +    height: DEVICE_WIDTH / 7,
Best case would be to make this auto flex to the height of the week row. Maybe removing height and making it setting `flex: 1` on it might work?

2016-10-31 18:55 UTC, hyb175 commented on components/styles.js
> +    height: DEVICE_WIDTH / 7,
Agreed. Maybe then I would set the height of the week row to default to `DEVICE_WIDTH / 7` as the solution for this was calculate the height of the whole calendar based on height of the row.

2016-10-31 19:11 UTC, christopherdro commented on components/styles.js
> +    height: DEVICE_WIDTH / 7,
Im not sure about, the week row just flex based on the content inside of it. So if someone decides to change the font size for each each day they won't run into any issues with overlapping content.

2016-12-06 06:46 UTC, hyb175 commented on components/styles.js
> +    height: DEVICE_WIDTH / 7,
Sorry for being non-responsive for quite some time, it's been quite busy. I understand the advantage of using flex here, but the way I am trying to fix this is by calculating the potential height of the calendar and in order to do that, I need to know the height of each row. If you think it's best to keep the flex here, the only way I can think of that could work is taking into account all the paddings and margins of each parts of the week-row to sum up to a row height, which seems a bit ugly and hard to maintain code. What do you think of this approach?

2017-02-03 23:08 UTC, hyb175 commented
@christopherdro Hi! Sorry it has been a while but I finally had time to re-think my approach and now came up with a completely different way of handling this. 
I determine the row height by use `onLayout` and debounce the calls so that it is not called too many times.
Credit to my co-workers @dvicory and @jonkessler

2017-02-07 18:00 UTC, christopherdro commented on components/Calendar.js
> +
You can remove this constructor and bind if you update line 172 to
`onWeekRowLayout = (event) => {}`

2017-02-07 18:00 UTC, christopherdro commented on components/Calendar.js
> +  onWeekRowLayout(event) {
see comment above

2017-02-07 18:34 UTC, hyb175 commented on components/Calendar.js
> +
Fixed in https://github.com/christopherdro/react-native-calendar/pull/73/commits/81260fcbdc9bf8d2243955156dadbcacbc063973

2017-02-07 18:41 UTC, christopherdro commented
Nice thanks.

2017-02-07 18:41 UTC, christopherdro approved these changes

2017-02-07 18:41 UTC, merged